### PR TITLE
Fix crash on readln()

### PR DESCRIPTION
**Pull request by LukasVykuka**

### CODE REVIEW

**Comment by pahill** [comment]
Hi @LukasVykuka, please could you provide a more elaborate description on why this change is needed? There is no readln in our repo, only a println.

**Comment by LukasVykuka** [comment]
Hi, this teplate is used in [this tutorial](https://kotlinlang.org/docs/native-get-started.html#update-the-application) where `readln` is called and it was quite hard to find solution for that crash.

**Comment by pahill** [comment]
Thank you for the link to the tutorial! Things make sense now!

Thanks for your PR, we will review.

**Comment by pahill** [comment]
Hi @LukasVykuka - we've decided to incorporate your suggestion in the docs rather than the template. We will be doing this soon. Thank you so much for your help! Have a great day.

**Pull request closed without merging**
